### ISSUE TITLE
Cannot start the server on OS X 10.9.5

### ISSUE THREAD

**Issue by elavoie** [Sable/McLab-Web#3]
(Canopy 64bit) Ericks-MacBook-Air-4:McLab-Web erick$ npm start

> mclab@0.0.2 start /Users/erick/Documents/Recherche/McLab-Web
> NODE_ENV=development node mcnode/app.js

module.js:341
    throw err;
    ^

Error: Cannot find module './config/config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/erick/Documents/Recherche/McLab-Web/mcnode/app.js:9:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! mclab@0.0.2 start: `NODE_ENV=development node mcnode/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mclab@0.0.2 start script 'NODE_ENV=development node mcnode/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mclab package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node mcnode/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mclab
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mclab
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erick/Documents/Recherche/McLab-Web/npm-debug.log

**Comment by elavoie** [comment]
Hi @emilrose, I tried running McLab-Web on my laptop and I got the previous error. I first did 'npm build' then did 'npm start'. Do you know what is going on?

**Comment by emilrose** [comment]
Looks like you don't have a config file. There is an example one in mcnode/config/config.example.js but several of the values are left as placeholders. 

There's a guide on how to set things up [here](https://github.com/Sable/McLab-Web/wiki/Setting-up-local-dev-environment-for-Node) that should help.

**Comment by elavoie** [comment]
Thanks. It now works. I will try packaging McLab-Web as a Sandstorm app ;-).
